<div style="text-align: right; background: #fff; margin: 0 0 -47px 0">
	<a href="<?php echo $this->url('zfcuser/logout') ?>">[Выйти]</a><br>

	<div style="text-align: left; padding-bottom: 50px; margin: 0 0 0 150px;">
		<!--		Категория-->
			<form action="" method="POST">
				<br><br>
				<label style="margin: 0 0 0 50px;">Название</label>
				<input name="title" value="">
				<br>
				<br>
				<label style="margin: 0 0 0 50px;">Описание</label>
				<textarea id="q_text" name="description"></textarea>
				<script type="text/javascript">
					CKEDITOR.replace( "q_text" );
				</script>
				<br>
				<br>
				<label style="margin: 0 0 0 50px;">Родительская категория</label>
				<select name="ref_id">
					<option value="0">Нет</option>
					<?php
					foreach ($category_all as $category) {
						?>
						<option value="<?=$category['id'] ?>"><?=$category['title'] ?></option>
						<?php } ?>
				</select>
				<label style="margin: 0 0 0 50px;">Изображение</label>
				<input id="img_text" name="image" value="" onchange="chengeImg();">
				<div style="margin: 20px 0 0 0; width: 500px;">
					<img id="cat_img" src="/images/">
				</div>
				<input style="margin: 20px 0 0 0;" type="submit" value="Добавить">
			</form>
		<!--		Категория-->

	</div>
</div>

<script>
	function chengeImg() {
		$('#cat_img').attr('src', '/images/' + $('#img_text').val());
	}
</script>