<div style="text-align: right; background: #fff; margin: 0 0 -47px 0">
	<a href="<?php echo $this->url('zfcuser/logout') ?>">[Выйти]</a><br>

	<div style="text-align: left; padding-bottom: 50px;">
		<form action="/admin/edit" method="post">
			<br><br>
			<label style="margin: 0 0 0 50px;">Категории <a style="font-size: 10px;" href="/admin/catadd">Добавить</a></label>
			<select style="margin: 0 0 0 50px;" name="cat_id">
				<?php
					foreach ($category_all as $category) {
				?>
				<option value="<?=$category['id'] ?>"><?=$category['title'] ?></option>
				<?php } ?>
			</select>
			<input type="submit" value="Изменить">
		</form>

		<form action="/admin/edit" method="post">
			<label style="margin: 0 0 0 50px;">Фирмы <a style="font-size: 10px;" href="/admin/firmadd">Добавить</a></label>
			<select style="margin: 0 0 0 50px;" name="firm_id">
				<?php
				foreach ($firms_all as $firm) {
					?>
					<option value="<?=$firm['id'] ?>"><?=$firm['title'] ?></option>
					<?php } ?>
			</select>
			<input type="submit" value="Изменить">
		</form>

		<form action="/admin/edit" method="post">
			<label style="margin: 0 0 0 50px;">Оборудование <a style="font-size: 10px;" href="/admin/prodadd">Добавить</a></label>
			<select style="margin: 0 0 0 50px;" name="prod_id">
				<?php
				foreach ($products_all as $product) {
					?>
					<option value="<?=$product['id'] ?>"><?=$product['title'] ?></option>
					<?php } ?>
			</select>
			<input type="submit" value="Изменить">
		</form>
	</div>
</div>