<?php
// module/Album/view/album/album/catalog.phtml:

$title = 'ООО "Представительство TECH" - Каталог';
$this->headTitle($title);
?>

<div class="center_catalog">

	<!---------------------------------Левое меню----------------------------->
	<div class="left_menu">
		<h4>КАТАЛОГ</h4>
		<ul>
			<?php
			foreach ($cat_list as $key => $cl) {
				if($key<7){
					echo '<li><a href="/catalog' . $cl['link'] . '">' . $cl['title'] . '</a></li>';
				}
			}
			?>
			<li style=" margin-top: 5px;"><a href="/catalog" style="color: #fff;"><b>Весь каталог...</b></a></li>
		</ul>
	</div>
	<!---------------------------------/Левое меню----------------------------->

	<div class="breadcrumb_auto"><a href="/">Главная</a> &larr; </div>

	<div class="main_left_menu_text_cat">
		<h3 id='category_title'><?=$category_all[0]['title'] ?></h3>
		<br>
		<p id="category_desc"><?=$category_all[0]['desc'] ?></p>
	</div>

	<!---------------------------------Галерея----------------------------->
	<div class="hit_prod" style="margin-left: 20px;">
		<?php
		foreach ($category_all as $key => $ha) {
			if($key == 0) {
				echo '<div id="'. $key .'" class="hit_prod_text" style="display:none">';
				echo '<a>Хит продаж</a>';
				echo '<a id="title_'. $key .'">' . $ha['title'] .'</a>';
				echo '<a id="desc_'. $key .'">' . $ha['desc'] .'</a>';
				echo '</div>';
				echo '<img id="'. $key .'" src="/images/' . $ha['image'] . '">';
			} else {
				echo '<div id="'. $key .'" class="hit_prod_text" style="display:none;">';
				echo '<a>Хит продаж</a>';
				echo '<a id="title_'. $key .'">' . $ha['title'] .'</a>';
				echo '<a id="desc_'. $key .'">' . $ha['desc'] .'</a>';
				echo '</div>';
				echo '<img id="'. $key .'" src="/images/' . $ha['image'] . '" style="opacity:0;">';
			}
		}
		?>
	</div>
	<!---------------------------------/Галерея----------------------------->

	<div style="clear: both"></div>
	<hr/>

	<!---------------------------------Центр---------------------------------->
	<?php
		foreach($category_all as $key => $ha) {
			echo '<ul class="category_list">';
				echo '<li>';
					echo "<h3>{$ha['title']}</h3>";
					echo '<a href="/catalog' . $ha['link'] . '">Перейти к категории...</a>';
				echo '</li>';
				echo '<li>';
					echo "<h4>{$ha['desc']}</h4>";
				echo '</li>';
				echo '<li>';
					echo '<img src="/images/' . $ha['image'] .'">';
				echo '</li>';
			echo '</ul>';
		}
	?>
	<!---------------------------------/Центр---------------------------------->

</div>