<?php
// module/Album/view/album/album/index.phtml:

$title = 'My albums';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
	<a href="<?php echo $this->url('auto', array('action'=>'add'));?>">Add new album</a>
</p>

<table class="table">
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($auto as $album) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($album->id);?></td>
		<td><?php echo $this->escapeHtml($album->title);?></td>
		<td><?php echo $this->escapeHtml($album->ref_id);?></td>
		<td><img src="<?php echo '/images/' . $album->image;?>" /></td>
	</tr>
	<?php endforeach; ?>
</table>