<?php
// module/Album/view/album/album/index.phtml:

$title = 'ООО "Представительство TECH"';
$this->headTitle($title);
?>


<table class="table">
	<tr>
		<th>Title</th>
		<th>Artist</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($auto as $album) : ?>
	<tr>
		<td><?php echo $this->escapeHtml($album->id);?></td>
		<td><?php echo $this->escapeHtml($album->title);?></td>
		<td><?php echo $this->escapeHtml($album->ref_id);?></td>
		<td><img src="<?php echo '/images/' . $album->image;?>" /></td>
	</tr>
	<?php endforeach; ?>
</table>