<div style="text-align: right; background: #fff; margin: 0 0 -47px 0">
	<a href="<?php echo $this->url('zfcuser/logout') ?>">[Выйти]</a><br>

	<div style="text-align: left;">
		<form action="" method="POST">
			<br><br>
			<label style="margin: 0 0 0 20px;">Категории <a href="/admin/catadd">Добавить</a></label>

			<select style="margin: 0 0 0 20px;">
				<?php
					foreach ($category_all as $category) {
				?>
				<option><?=$category['title'] ?></option>
				<?php } ?>
			</select>
			<br><br>
			<label style="margin: 0 0 0 20px;">Фирмы <a href="/admin/firmadd">Добавить</a></label>
			<select style="margin: 0 0 0 20px;">
				<?php
				foreach ($firms_all as $firm) {
					?>
					<option><?=$firm['title'] ?></option>
					<?php } ?>
			</select>
			<br><br>
			<label style="margin: 0 0 0 20px;">Оборудование <a href="/admin/prodadd">Добавить</a></label>
			<select style="margin: 0 0 0 20px;">
				<?php
				foreach ($products_all as $product) {
					?>
					<option><?=$product['title'] ?></option>
					<?php } ?>
			</select>
			<br><br><br>
		</form>
	</div>
</div>