<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle() ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/auto.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

		<!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
									  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
									  ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

	</head>
	<body>
		<div class="main">
			<div class="container">
				<div class="menu_auto">
					<div class="menu_logo"></div>
					<a class="menu_logo_text">TECH <span>KMV.RU</span></a>
					<a class="menu_text">профессиональное автосервисное оборудование</a>
					<div class="menu_block">
						<a class="current" href=""><span class="gran"></span>Главная</a>
						<a href=""><span class="gran"></span>О нас</a>
						<a href=""><span class="gran"></span>Продукция</a>
						<a href=""><span class="gran"></span>Новинки</a>
						<a href=""><span class="gran"></span>Скидки</a>
						<a href=""><span class="gran"></span>Контакты</a>
					</div>
				</div>
				<div class="center">
				</div>
<!--				--><?php //echo $this->content; ?>
				<div class="footer">
					<div class="footer_up"></div>
				</div>
				<footer >
				</footer>
			</div> <!-- /container -->
		</div>

		<?php echo $this->inlineScript() ?>
	</body>
</html>
