<?php echo $this->doctype(); ?>

<html lang="en">
	<head>
		<meta charset="utf-8">
		<?php echo $this->headTitle() ?>

		<?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

		<!-- Le styles -->
		<?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
						->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
						->prependStylesheet($this->basePath() . '/css/style.css')
						->prependStylesheet($this->basePath() . '/css/auto.css')
						->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

		<!-- Scripts -->
		<?php echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
									  ->prependFile($this->basePath() . '/js/bootstrap.min.js')
									  ->prependFile($this->basePath() . '/js/jquery.min.js') ?>

	</head>
	<body>
		<div class="main">
			<div class="container">
				<div class="menu_auto">
					<div class="menu_logo"></div>
					<a class="menu_logo_text">TECH <span>KMV.RU</span></a>
					<a class="menu_text">профессиональное автосервисное оборудование</a>

<!---------------------------------Меню----------------------------->
					<div class="menu_block">
						<a class="current" href=""><span class="gran"></span>Главная</a>
						<a href=""><span class="gran"></span>О нас</a>
						<a href=""><span class="gran"></span>Продукция</a>
						<a href=""><span class="gran"></span>Новинки</a>
						<a href=""><span class="gran"></span>Скидки</a>
						<a href=""><span class="gran"></span>Контакты</a>
					</div>
				</div>
<!---------------------------------/Меню----------------------------->

				<div class="center">

<!---------------------------------Левое меню----------------------------->
					<div class="left_menu">
						<h4>КАТАЛОГ</h4>
						<ul>
							<li><a href="#">Стенды Развал Схождения</a></li>
							<li><a href="#">Стапеля для кузовных работ</a></li>
							<li><a href="#">Подъемное оборудование</a></li>
							<li><a href="#">Компрессоры</a></li>
							<li><a href="#">Шиномонтажное оборудование</a></li>
							<li><a href="#">Дископравочные станки</a></li>
							<li><a href="#">Шиноремонтные материалы</a></li>
							<li><a href="#">Балансировочное оборудование</a></li>
						</ul>
					</div>
<!---------------------------------/Левое меню----------------------------->



					<div class="main_left_menu_text">
						С 2001 г. компания <span>ИП Купцова</span>  и <span>ООО "Представительство ТЕСН"</span> одна из первых на рынке автосервисного
						оборудования в ЮФО занимается продажей профессионального как иностранного, так и отечественного оборудования для автосервисов.
						<br>
						<br>
						Специализируется на поставке всего спектра профессионального оборудования для автосервисов и СТО. Ориентируясь на высокое
						качество предоставляемых услуг и достойные эксплуатационные характеристики реализуемого оборудования, мы смогли заработать
						репутацию надежного парнера, нацеленного на взаимовыгодное долгосрочное сотрудничество с каждым клиентом.
					</div>


<!---------------------------------Хит продаж----------------------------->
					<div class="arrow_hit left_arr">
						<img src="/images/arrow_left.png" />
					</div>
					<div class="hit_prod">
					</div>
					<div class="arrow_hit right_arr">
						<img src="/images/arrow_right.png" />
					</div>
<!---------------------------------/Хит продаж----------------------------->

<!---------------------------------Лого компаний----------------------------->
					<div class="comp_logos"></div>
<!---------------------------------/Лого компаний----------------------------->

<!---------------------------------Шары----------------------------->
					<div class="circles">
						<ul class="ch-grid">
							<li>
								<div class="ch-item ch-img-1">
									<div class="ch-info">
										<h3>Отличное качество!</h3>
										<p>by Angela Duncan <a href="http://drbl.in/eOPF">View on Dribbble</a></p>
									</div>
								</div>
							</li>
							<li>
								<div class="ch-item ch-img-2">
									<div class="ch-info">
										<h3>Огромные скидки</h3>
										<p>by Antonio F. Mondragon <a href="http://drbl.in/eKMi">View on Dribbble</a></p>
									</div>
								</div>
							</li>
							<li>
								<div class="ch-item ch-img-3">
									<div class="ch-info">
										<h3>Гарантия -ГОД!</h3>
										<p>by Charlie Wagers <a href="http://drbl.in/ekhp">View on Dribbble</a></p>
									</div>
								</div>
							</li>
						</ul>
					</div>
<!---------------------------------/Шары----------------------------->

<!---------------------------------Текст------------------------------------->
					<div class="main_text_left">
						Morbi fringilla commodo ipsum. **Suspendisse volutpat** congue massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultricies euismod nisi. Gravida mollis, metus *lacus consequat* es.Vestibulum varius accumsan leo. Pellentesque rhoncus mauris a sapien. Proin tincidunt velit sit amet est. Nulla tempor ligula porttitor sapien. Donec lorem mi fermentum at : * Ut semsddper elisat sed nullateli * Us ac nisi interdum fau * Erdum fau utilotieu * Betagor chaligonatu ### Donec lorem mi #### luctus diam Suspendisse pellentesque luctus diam. [Diem](http://diem-project.org/) fusce sem lorem, convallis ut, dictum at, blandit eu, erat; Etiam et **nulla convallis** risus adipiscing consectetur. *Morbi velit massa*, dapibus at, pharetra at, auctor ornare, risus. #### enim nisl Nunc lobortis, nulla et auctor ultricies, enim nisl *venenatis turpis*, quis pharetra lectus sapien fermentum mauris. Aliquam erat volutpat.
					</div>
					<div class="main_text_right">
						Morbi fringilla commodo ipsum. **Suspendisse volutpat** congue massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras ultricies euismod nisi. Gravida mollis, metus *lacus consequat* es.Vestibulum varius accumsan leo. Pellentesque rhoncus mauris a sapien. Proin tincidunt velit sit amet est. Nulla tempor ligula porttitor sapien. Donec lorem mi fermentum at : * Ut semsddper elisat sed nullateli * Us ac nisi interdum fau * Erdum fau utilotieu * Betagor chaligonatu ### Donec lorem mi #### luctus diam Suspendisse pellentesque luctus diam. [Diem](http://diem-project.org/) fusce sem lorem, convallis ut, dictum at, blandit eu, erat; Etiam et **nulla convallis** risus adipiscing consectetur. *Morbi velit massa*, dapibus at, pharetra at, auctor ornare, risus. #### enim nisl Nunc lobortis, nulla et auctor ultricies, enim nisl *venenatis turpis*, quis pharetra lectus sapien fermentum mauris. Aliquam erat volutpat.
					</div>

					<!---------------------------------/Текст------------------------------------->


<!--					--><?php //echo $this->content; ?>
				</div>
				<div class="footer">
					<div class="footer_up"></div>
				</div>
				<footer >
				</footer>
			</div> <!-- /container -->
		</div>

		<?php echo $this->inlineScript() ?>
	</body>
</html>
